tasks_application/tasks/urls.py
from django.conf.urls.defaults import patterns, include, url

from tasks.forms import InboxForm, TaskForm, ProjectForm
from tasks.models import Project
from tasks.models import Task

from django.views.generic.simple import direct_to_template

from django.conf import settings

urlpatterns = patterns('tasks.views', 
    #~ filters
    (r'^project/open/(?P<object_id>\d+)/$', 'project_set', {}, 'tasks_project_set'), 
    (r'^filter/highlighted/(?P<value>\d+)/$', 'filter_highlighted', {}, 'tasks_filter_highlighted'), 
    
    #~ project
    (r'^project/$', 'project_general', {}, 'tasks_project_general'), 
    (r'^project/new/$', 'create_user_owned_object', {'model':Project, 'form_class':ProjectForm, 'post_save_redirect':settings.HOME_URL}, 'tasks_project_new'), 
    (r'^project/(?P<object_id>\d+)/close/$', 'project_close', {}, 'tasks_project_close'), 
    
    #~ tasks
    (r'^task/(?P<object_id>\d+)/edit/$', 'task_update', {'form_class':TaskForm, 'post_save_redirect':settings.HOME_URL}, 'tasks_task_edit'), 
    (r'^task/(?P<object_id>\d+)/duplicate/$', 'task_duplicate', {}, 'tasks_task_duplicate'), 
    (r'^task/(?P<object_id>\d+)/detail/$', 'task_detail', {}, 'tasks_task_detail'), 
    (r'^task/(?P<object_id>\d+)/block/$', 'task_toggle_block', {}, 'tasks_task_block'), 
    (r'^task/(?P<object_id>\d+)/archive/$', 'task_toggle_archived', {}, 'tasks_task_archive'), 
    (r'^task/(?P<object_id>\d+)/delay/$', 'task_toggle_delay', {}, 'tasks_task_delay'), 
    (r'^task/(?P<object_id>\d+)/highlight/$', 'task_toggle_highlight', {}, 'tasks_task_highlight'), 
    
    (r'^process/update/(?P<object_id>\d+)/$', 'task_update', {'form_class':TaskForm, 'post_save_redirect':settings.HOME_URL+'tasks/process/'}, 'tasks_process_update'), 
    (r'^inbox/insert/$', 'task_create', {'form_class':InboxForm, 'post_save_redirect':settings.HOME_URL}, 'tasks_inbox_insert'), 
    (r'^process/$', 'process', {}, 'tasks_process'), 
    
    #~ json
    (r'^project/json/', 'project_json', {}, 'tasks_project_json'), 
    (r'^task/json/', 'task_json', {}, 'tasks_task_json'), 
)

urlpatterns += patterns('django.views.generic', 
    (r'^project/(?P<object_id>\d+)/delete/$', 'create_update.delete_object', {'model':Project, 'post_delete_redirect':settings.HOME_URL}, 'tasks_project_delete'), 
    (r'^project/(?P<object_id>\d+)/edit/$', 'create_update.update_object', {'form_class':ProjectForm, 'post_save_redirect':settings.HOME_URL}, 'tasks_project_edit'), 
    (r'^task/(?P<object_id>\d+)/delete/$', 'create_update.delete_object', {'model':Task, 'post_delete_redirect':settings.HOME_URL}, 'tasks_task_delete'), 
    ('^archive/$', 'simple.direct_to_template', {'template': 'tasks/task_archived.html'}, 'tasks_archived'), 
)

tasks_application/urls.py
# -*- coding: utf-8 *-*
from django.conf.urls.defaults import patterns, include

from django.contrib import admin
admin.autodiscover()

from django.conf import settings

urlpatterns = patterns('',
    #~ (r'^/accounts/login/','tasks.views.login_view',{}),
    #~ (r'^/accounts/logout/$','tasks.views.logout_view',{}),

    (r'^$', 'tasks.views.index', {}, 'tasks_home'),
    (r'^tasks/', include("tasks.urls")),

    (r'^accounts/login/$',
        'django.contrib.auth.views.login', {}, 'accounts_login'),
    (r'^accounts/logout/$',
        'django.contrib.auth.views.logout',
        {'next_page': settings.HOME_URL}, 'accounts_logout'),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.RUTA_BASE + '/static'}, 'static')
)

tasks_application/tasks/models.py
from django.db import models
from django.contrib.auth.models import User

from django.core.urlresolvers import reverse

SIZE_CHOICES = (
    #~ (0, 'In Box'),
    (1, '- de 5 minutos'),
    (2, '+ de 5 minutos'),
    (3, '+ de 2 horas'),
    (4, '?'),
)

#~ :D
class ProjectManager(models.Manager):
    
    def get_or_create_by_owner_and_title(self, owner, title):
        p = None
        ps = self.filter(owner = owner).filter(title = title)
        if ps:
            p = ps[0]
        else:
            if title:
                p = self.model(title = title,owner = owner)
                p.save()
        return p


class TaskManager(models.Manager):
    
    def toggle_highlight(self, object_id):
        try:
            obj = Task.objects.get(pk = object_id)
            obj.toggle_highlight()
        except:
            pass
            
    def toggle_block(self, object_id):
        try:
            obj = Task.objects.get(pk = object_id)
            obj.toggle_block()
        except:
            pass
        
    def toggle_archived(self, object_id):
        try:
            obj = Task.objects.get(pk = object_id)
            obj.toggle_archived()
            return obj
        except:
            pass
    
    def toggle_delay(self, object_id):
        try:
            obj = Task.objects.get(pk = object_id)
            obj.toggle_delay()
        except:
            pass

    def duplicate(self, object_id):
        try:
            obj = self.get(pk = object_id)
            obj.pk = None
            obj.title = 'Copia de: '+obj.title
            obj.save()
        except:
            pass
        return obj


class Project(models.Model):
    owner = models.ForeignKey(User, verbose_name = 'Usuario')
    title = models.CharField(max_length = 255, verbose_name = 'Nombre')
    is_closed = models.BooleanField(blank = True, default = 0, verbose_name = 'Cerrado')
    last_access = models.DateTimeField(auto_now_add = True, null = True)
    
    objects = ProjectManager()
    
    def to_json(self):
        return '{"title":"'+self.title+'"}'

    def count_tasks(self):
        return self.task_set.all().count()
        
    def __unicode__(self):
        return self.title


class Task(models.Model):
    title = models.CharField(max_length = 255, verbose_name = 'Tarea')
    size = models.IntegerField(default = 0, choices = SIZE_CHOICES, verbose_name = 'Magnitud')
    project = models.ForeignKey(Project, verbose_name = 'Proyecto',blank = True, null = True, default = '')
    detail = models.TextField(max_length = 2000,blank = True, null = True, verbose_name = 'Detalle')
    is_blocked = models.BooleanField(blank = True, default = 0, verbose_name = 'Bloqueada')
    is_archived = models.BooleanField(blank = True, default = 0, verbose_name = 'Archivada')
    is_delayed = models.BooleanField(blank = True, default = 0, verbose_name = 'Pospuesta')
    is_highlighted = models.BooleanField(blank = True, default = 0, verbose_name = 'Destacada')
            
    objects = TaskManager()
    
    def toggle_block(self):
        if self.is_blocked:
            self.is_blocked = False
        else:
            self.is_blocked = True
        self.save()
        
    def toggle_archived(self):
        if self.is_archived == False:
            self.is_archived = True
            self.is_delayed = False
            self.is_highlighted = False
            self.is_blocked = False
        else:
            self.is_archived = False
        self.save()
        
    def toggle_delay(self):
        if self.is_delayed:
            self.is_delayed = False
        else:
            self.is_delayed = True
        self.save()
        
    def toggle_highlight(self):
        if self.is_highlighted:
            self.is_highlighted = False
        else:
            self.is_highlighted = True
        self.save()
        
    def absolute_url(self):
        return reverse('tasks_task_edit', args = [self.id])
        
    def __unicode__(self):      
        return self.title

tasks_application/tasks/views.py
# -*- coding: utf-8 *-*
from datetime import datetime

from django.contrib import messages
#from django.contrib.auth.views import redirect_to_login
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.translation import ugettext
from django.views.generic.create_update import (get_model_and_form_class,
                                                lookup_object, redirect)

from tasks.forms import (TaskForm, ProjectForm)
from tasks.models import (Task, Project)


def index(request):
    r = {}
    return render_to_response('tasks/home.html', r, RequestContext(request))


def project_set(request, object_id):
    try:
        obj = Project.objects.get(pk=object_id)
        obj.last_access = datetime.now()
        request.session['current_project'] = obj
        obj.save()
    except:
        request.session['current_project'] = None
        pass
    return HttpResponseRedirect(reverse('tasks_home'))


def process(request):
    r = {}
    r['inbox_list'] = Task.objects.filter(size=0)
    inbox_first = None
    if r['inbox_list']:
        inbox_first = r['inbox_list'][0]
    r['form'] = TaskForm(instance=inbox_first)
    r['inbox_first'] = inbox_first
    if inbox_first:
        return render_to_response('tasks/process.html', r,
                                  RequestContext(request))
    else:
        return HttpResponseRedirect(reverse('tasks_home'))


def task_duplicate(request, object_id):
    obj = Task.objects.duplicate(object_id)
    if obj:
        return HttpResponseRedirect(
                    reverse('tasks_task_edit', kwargs={'object_id': obj.id}))
    else:
        return HttpResponseRedirect(reverse('tasks_home'))


def task_detail(request, object_id):
    try:
        r = {}
        r['object'] = Task.objects.get(pk=object_id)
    except:
        pass
    return render_to_response('tasks/task_detail.html', r,
                              RequestContext(request))


def project_close(request, object_id):
    try:
        obj = Project.objects.get(pk=object_id)
        if obj.is_closed:
            obj.is_closed = False
        else:
            obj.is_closed = True
        obj.save()
        if obj == request.session.get('current_project'):
            return project_set(request, object_id=0)
    except:
        pass
    return HttpResponseRedirect(reverse('tasks_project_general'))


def project_general(request):
    r = {}
    r['form'] = ProjectForm()
    r['project_list'] = Project.objects.filter(owner=request.user)
    return render_to_response('tasks/project_general.html', r,
                              RequestContext(request))


def create_user_owned_object(request,
                             model=None, template_name=None,
                             extra_context=None, post_save_redirect=None,
                             login_required=False, context_processors=None,
                             form_class=None):
    if extra_context is None:
        extra_context = {}
    if login_required and not request.user.is_authenticated():
        return redirect_to_login(request.path)

    model, form_class = get_model_and_form_class(model, form_class)
    if request.method == 'POST':
        form = form_class(request.POST, request.FILES)
        if form.is_valid():
            #~ new_object = Task()
            new_object = form.save(commit=False)
            #~ relation with session user
            new_object.owner = request.user
            new_object.save()

            msg = ugettext("The %(verbose_name)s was created successfully.") %\
                                    {"verbose_name": model._meta.verbose_name}
            messages.success(request, msg, fail_silently=True)
            return redirect(post_save_redirect, new_object)
    else:
        form = form_class()

    # Create the template, context, response
    if not template_name:
        template_name = "%s/%s_form.html" % (model._meta.app_label,
                                             model._meta.object_name.lower())

    return render_to_response(template_name, {'form': form},
                              RequestContext(request))

    if not template_name:
        template_name = "%s/%s_form.html" % (model._meta.app_label,
                                             model._meta.object_name.lower())
    t = template_loader.get_template(template_name)
    c = RequestContext(request, {
        'form': form,
        template_object_name: obj,
    }, context_processors)
    apply_extra_context(extra_context, c)
    response = HttpResponse(t.render(c))
    populate_xheaders(request, response, model,
                      getattr(obj, obj._meta.pk.attname))
    return response


def task_update(request, model=None,
                object_id=None, slug=None,
                slug_field='slug', template_name=None,
                extra_context=None, post_save_redirect=None,
                login_required=False, context_processors=None,
                template_object_name='object', form_class=None):
    if extra_context is None:
        extra_context = {}
    if login_required and not request.user.is_authenticated():
        return redirect_to_login(request.path)
    model, form_class = get_model_and_form_class(model, form_class)
    obj = lookup_object(model, object_id, slug, slug_field)

    if request.method == 'POST':
        #~ recuperar o crear el proyecto
        p = Project.objects.get_or_create_by_owner_and_title(
                               request.user, request.POST.get('project_title'))
        form = form_class(request.POST, request.FILES, instance=obj)
        del form.fields['project']
        if form.is_valid():
            obj = form.save(commit=False)
            obj.project = p
            obj.save()
            msg = ugettext("The %(verbose_name)s was updated successfully.") %\
                                    {"verbose_name": model._meta.verbose_name}
            messages.success(request, msg, fail_silently=True)
            if "_continue" not in request.POST:
                return redirect(post_save_redirect, obj)
    else:
        form = form_class(instance=obj)
    if not template_name:
        template_name = "%s/%s_form.html" % (
                        model._meta.app_label, model._meta.object_name.lower())
    return render_to_response(template_name, {'form': form, 'object': obj},
                              RequestContext(request))


def task_create(request, model=None,
                template_name=None, extra_context=None,
                post_save_redirect=None, login_required=False,
                context_processors=None, form_class=None):

    if extra_context is None:
        extra_context = {}
    if login_required and not request.user.is_authenticated():
        return redirect_to_login(request.path)

    model, form_class = get_model_and_form_class(model, form_class)
    if request.method == 'POST':
        p = Project.objects.get_or_create_by_owner_and_title(
                        request.user, request.POST.get('project_title_inbox'))
        form = form_class(request.POST, request.FILES)
        if form.is_valid():
            new_object = form.save(commit=False)
            new_object.project = p
            new_object.save()
            msg = ugettext("The %(verbose_name)s was created successfully.") %\
                                    {"verbose_name": model._meta.verbose_name}
            messages.success(request, msg, fail_silently=True)
            return redirect(post_save_redirect, new_object)
    else:
        form = form_class()
    if not template_name:
        template_name = "%s/%s_insert_form.html" % (
                        model._meta.app_label, model._meta.object_name.lower())
    return render_to_response(template_name, {'form': form},
                              RequestContext(request))


def project_json(request):
    r = {}
    if request.method == 'GET':
        q = request.GET.get('q')
        #~ from django.core import serializers
        #~ data = serializers.serialize("json", )
        r['object_list'] = Project.objects.filter(owner=request.user).filter(
                                     is_closed=False).filter(title__contains=q)
        pass
    return render_to_response('tasks/project_json.html', r,
                              RequestContext(request))


def task_json(request):
    r = {}
    if request.method == 'GET':
        q = request.GET.get('q')
        project_list = Project.objects.filter(owner=request.user)
        pre_list = Task.objects.filter(project__in=project_list)
        pre_list1 = pre_list.filter(title__contains=q)
        pre_list2 = pre_list.filter(detail__contains=q)
        #~ r['object_list'] = Task.objects.filter(title__contains = q)
        r['object_list'] = pre_list1 | pre_list2
        # filtrar por detail
        pass
    return render_to_response('tasks/task_json.html', r,
                              RequestContext(request))


def filter_highlighted(request, value):
    request.session['filter_highlighted'] = value
    return HttpResponseRedirect(reverse('tasks_home'))


def task_toggle_block(request, object_id):
    Task.objects.toggle_block(object_id)
    return HttpResponseRedirect(reverse('tasks_home'))


def task_toggle_highlight(request, object_id):
    Task.objects.toggle_highlight(object_id)
    return HttpResponseRedirect(reverse('tasks_home'))


def task_toggle_delay(request, object_id):
    Task.objects.toggle_delay(object_id)
    return HttpResponseRedirect(reverse('tasks_home'))


def task_toggle_archived(request, object_id):
    obj = Task.objects.toggle_archived(object_id)
    if obj:
        if not obj.is_archived:
            return HttpResponseRedirect(reverse('tasks_task_edit',
                                                kwargs={'object_id': obj.id}))
    return HttpResponseRedirect(reverse('tasks_home'))

tasks_application/tasks/templates/tasks/_inbox_form.html
<div id="inbox_form">
    <script>
        $(document).ready(function(){
            
            project_selector_id='id_project_title_inbox';
            {%if current_project%}
                $("#"+project_selector_id).val('{{current_project|escapejs}}');
                $('#id_title').focus();
            {%else%}
                $('#'+project_selector_id).focus();
            {%endif%}
            {%include '_project_selector_js.html'%}
        });
    </script>

    <b>Carga rápida:</b>
    <b>Ingresa una Tarea al Inbox.</b>
    <form method="post" action="{%url tasks_inbox_insert%}">
        {{inbox_form.as_p}}
        <p><input type="submit" value="Grabar"></p>
    </form>
</div>

tasks_application/tasks/templates/tasks/_open_project_box.html
<div class="tasks_pending_list_project_label"><!-- project {{object.project}}-->
<h3 >{{object.project}}</h3>

tasks_application/tasks/templates/tasks/_open_size_box.html
<div class="tasks_pending_list_label"><!-- div que contiene todo el size {{object.get_size_display}} -->
<h2>{{object.get_size_display}}</h2>    

tasks_application/tasks/templates/tasks/_task_actions.html
{%if object.id%}
<a title="Borrar definitivamente" href="{%url tasks_task_delete object.id%}">Eliminar</a>
{%endif %}
<input type="submit" value="Save">  
<input type="submit" value="Save and continue editing" name="_continue">

tasks_application/tasks/templates/tasks/inbox_form.html
<div id="inbox_form">
    <script>
        $(document).ready(function(){
            project_selector_id='id_project_title_inbox';
            {%if current_project%}$("#"+project_selector_id).val('{{current_project|escapejs}}');{%endif%}
            {%include 'project_selector_js.html'%}
        });
    </script>

    <h3>Ingresa una Tarea al Inbox:</h3>
    <form method="post" action="{%url tasks_inbox_insert%}">
        {{inbox_form.as_p}}
        <p><input type="submit"> </p>
    </form>
</div>

tasks_application/tasks/templates/tasks/project_confirm_delete.html
{%extends 'base.html'%}
    {%block title%} {{object}} {%endblock%}
    {%block content%}
        <h3>Carpeta</h3>
        <table >
            <tr><td> 
            <strong>{{object}}</strong><br>
            {{object.detail}}
                <form method="post" action="{%url tasks_project_delete object.id%}">
                    <table>
                        <tr>
                            <td></td>
                            <td><input type="submit" value="Borrar definitivamente"> </td>
                        </tr>
                    </table>
                </form>
            </td></tr>
        </table>                
    {%endblock%}
    

tasks_application/tasks/templates/tasks/project_float.html
<div class="project {%if object.is_closed %}closed{%else%}{%endif%}">
    <a title="Editar" href="{%url tasks_project_edit object.id%}">{{ object.title }}</a><br>
    <a class="button close" title="{%if object.is_closed%}Abrir{%else%}Cerrar{%endif%}" href="{%url tasks_project_close object.id%}"></a>
    {%if not object.id == current_project.id %}
        <a class="button activate" title="Activar Proyecto" href="{%url tasks_project_set object.id%}"></a>
    {%endif%}
    <a class="button delete" title="Borrar definitivamente" href="{%url tasks_project_delete object.id%}"></a>
</div>

tasks_application/tasks/templates/tasks/project_form.html
{%extends 'base.html'%}
    {%block title%}Nuevo Proyecto{%endblock%}
    {%block inbox%}
    {%endblock%}
    {%block content%}
        <h3>Proyecto</h3>
        <table >
            <tr><td> 
                <form method="post" action="">
                <table>
                   {{form}}
                    <tr>
                        <td></td>
                        <a title="Borrar definitivamente" href="{%url tasks_project_delete object.id%}">Eliminar</a>
                        <td><input type="submit" value="Save">  </td>
                    </tr>
                </table>
                </form>
            </td></tr>
        </table>                
    {%endblock%}
    

tasks_application/tasks/templates/tasks/project_json.html
[{%for obj in object_list%}{%if not forloop.first%},{%endif%}{ "title":"{{obj.title|safe}}","id":"{{obj.id}}"}{%endfor%}]
{%comment%}{%endcomment%}

tasks_application/tasks/templates/tasks/task_actions.html
{%if object.id%}
<a title="Borrar definitivamente" href="{%url tasks_task_delete object.id%}">Eliminar</a>
{%endif %}
<input type="submit" value="Save">  
<input type="submit" value="Save and continue editing" name="_continue">

tasks_application/tasks/templates/tasks/task_archived.html
{%extends 'base.html'%}
    {%block title%}Archivo{%endblock%}
    {%block content%}
        
        <div id="task_archived">
            <table>
                <tr><td>
                    <h2>Tareas archivas:</h2>
                        {%if archived_tasks%}
                            {%for object in archived_tasks%}
                                {%include 'tasks/_task_float.html'%}
                            {%endfor%}
                        {%else%}
                        <p>No tasks are available.</p>
                    {%endif%}
                </td></tr>
            </table>
        </div>
    {%endblock%}
    

tasks_application/tasks/templates/tasks/task_detail.html
{%extends 'base.html'%}
{%block title%} Detalles de: {{object}} {%endblock%}
{%block content%}
<h3>Tarea</h3>
    <table >
        <tr><td> 
        <strong>{{object}}</strong><br>
        {{object.detail|linebreaks}}
        <a href="{%url tasks_task_delete object.id%}">Borrar</a>
        </td></tr>
    </table>                
{%endblock%}

tasks_application/tasks/templates/tasks/task_insert_form.html
{%extends 'base.html'%}
    {%block title%} {{object}} {%endblock%}
    {%block extra_head%}
        <script>
            $(document).ready(function(){
                project_selector_id='id_project_title_inbox';
                //$("#"+project_selector_id).val('{{object.project|escapejs}}');
                {%include '_project_selector_js.html'%}
            });
        </script>
    {%endblock%}
    
    {%block inbox%}{%endblock%}
    
    {%block content%}
        <h3>Tarea</h3>
        <table>
            <tr><td> 
                <form method="post" action="">
                    <table>
                        <tr>
                            <td></td>
                            <td>
                                {%include 'tasks/_task_actions.html'%}
                            </td>
                        </tr>
                           {{form}}
                        <tr>
                            <td></td>
                            <td>
                                {%include 'tasks/_task_actions.html'%}
                            </td>
                        </tr>
                    </table>
                </form>
            </td></tr>
        </table>
    {%endblock%}
    

tasks_application/tasks/templates/tasks/task_json.html
{%for obj in object_list%}{{obj.project|safe}}: {{obj.title|safe}}{%if obj.detail %} (+) {% endif %}|{{obj.absolute_url}}
{%endfor%}{%comment%}{%if not forloop.first%},{%endif%}{%endcomment%}